# Generated by Django 5.1.7 on 2025-04-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='learnMode',
            field=models.CharField(choices=[('GUESS_A', 'Guessa'), ('GUESS_B', 'Guessb'), ('RANDOM', 'Random')], default='GUESS_A', max_length=100),
        ),
    ]
