# Generated by Django 5.1.7 on 2025-04-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_preference_learnmode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='learnMode',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('REVERSED', 'Reversed')], default='NORMAL', max_length=100),
        ),
    ]
