# Generated by Django 5.1.7 on 2025-05-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_preference_learnmode'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='learnFailWordsPerc',
            field=models.FloatField(default=0.01),
        ),
        migrations.AddField(
            model_name='preference',
            name='learnFavoriteWordPerc',
            field=models.FloatField(default=0.01),
        ),
        migrations.AddField(
            model_name='preference',
            name='learnNewWordsPerc',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='preference',
            name='learnSuccessWordsPerc',
            field=models.FloatField(default=0.01),
        ),
        migrations.AddField(
            model_name='preference',
            name='learnUserWordsPerc',
            field=models.FloatField(default=1),
        ),
    ]
