# Generated by Django 5.1.7 on 2025-05-09 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_preference_learnfailwordsperc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preference',
            old_name='learnFavoriteWordPerc',
            new_name='learnFavoriteWordsPerc',
        ),
    ]
