# Generated by Django 5.1.7 on 2025-05-20 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_learnfavoritewordperc_preference_learnfavoritewordsperc'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='learnDeck',
            field=models.CharField(choices=[('ALL', 'All'), ('USER', 'User'), ('FAVORITE', 'Favorite')], default='ALL', max_length=100),
        ),
    ]
