# Generated by Django 5.1.7 on 2025-05-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_preference_learndeck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='learnDeck',
            field=models.CharField(choices=[('ALL', 'Created By Everyone'), ('USER', 'Created By Me'), ('FAVORITE', 'My Favorite')], default='ALL', max_length=100),
        ),
    ]
