# Generated by Django 5.1.7 on 2025-04-09 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('french', models.CharField(max_length=100)),
                ('korean', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('word_class', models.CharField(choices=[('UNDEFINE', 'Undf'), ('NOUN', 'Noun'), ('VERB', 'Verb'), ('ADJ', 'Adjective'), ('PRON', 'Pronoun'), ('ADV', 'Adverb'), ('END', 'Ending'), ('PART', 'Particule'), ('DET', 'Determiner'), ('INTJ', 'Interjection'), ('NUM', 'Numeral')], default='UNDEFINE', max_length=20)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
