# Generated by Django 5.1.7 on 2025-04-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_word_en_word_fr_word_kr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word_class',
            field=models.CharField(choices=[('undef', 'undefine'), ('n', 'noun'), ('v', 'verb'), ('adj', 'adjective'), ('pron', 'pronon'), ('adv', 'adverb'), ('suff', 'ending'), ('part', 'particule'), ('det', 'determiner'), ('int', 'interjection'), ('num', 'numeral')], default='undef', max_length=20),
        ),
    ]
