# Generated by Django 5.1.7 on 2025-04-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_remove_word_english_remove_word_french_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
