# Generated by Django 5.1.7 on 2025-04-10 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languageA', models.CharField(choices=[('FR', 'Français'), ('EN', 'English'), ('KR', '한국어')], default='FR', max_length=20)),
                ('languageB', models.CharField(choices=[('FR', 'Français'), ('EN', 'English'), ('KR', '한국어')], default='KR', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
