# Generated by Django 5.1.7 on 2025-04-05 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='word',
            name='word_class',
            field=models.CharField(choices=[('UNDEFINE', 'Undf'), ('NOUN', 'Noun'), ('VERB', 'Verb'), ('ADJ', 'Adjective'), ('PRON', 'Pronoun'), ('ADV', 'Adverb'), ('END', 'Ending'), ('PART', 'Particule'), ('DET', 'Determiner'), ('INTJ', 'Interjection'), ('NUM', 'Numeral')], default='UNDEFINE', max_length=20),
        ),
    ]
