# Generated by Django 5.1.7 on 2025-04-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_alter_word_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='english',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
