# Generated by Django 5.1.7 on 2025-04-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_word_english'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='EN',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='word',
            name='FR',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='word',
            name='KR',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
