# Generated by Django 5.1.7 on 2025-05-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_alter_score_user_alter_score_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
