# Generated by Django 5.1.7 on 2025-05-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_score_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
